import frappe 
from frappe.custom.doctype.property_setter.property_setter import make_property_setter

def create_property_setter():
    make_property_setter('Production Plan', 'get_sub_assembly_items', 'hidden', 1, 'Check')
    make_property_setter('Production Plan', 'sub_assembly_items', 'hidden', 1, 'Check')
    make_property_setter('Work Order','production_plan_item','hidden', 1, 'Check')
    make_property_setter('Item','section_break_11','hidden', 1, 'Check')
    make_property_setter('Item','sb_barcodes','hidden', 1, 'Check')
    make_property_setter('Item','unit_of_measure_conversion','hidden', 1, 'Check')
    make_property_setter('Item','serial_nos_and_batches','hidden', 1, 'Check')
    make_property_setter('Item','variants_section','hidden', 1, 'Check')
    make_property_setter('Item','purchase_details','hidden', 1, 'Check')
    make_property_setter('Item','supplier_details','hidden', 1, 'Check')
    make_property_setter('Item','foreign_trade_details','hidden', 1, 'Check')
    make_property_setter('Item','sales_details','hidden', 1, 'Check')
    make_property_setter('Item','deferred_revenue','hidden', 1, 'Check')
    make_property_setter('Item','deferred_expense_section','hidden', 1, 'Check')
    make_property_setter('Item','customer_details','hidden', 1, 'Check')
    make_property_setter('Item','item_tax_section_break','hidden', 1, 'Check')
    make_property_setter('Item','inspection_criteria','hidden', 1, 'Check')
    make_property_setter('Item','manufacturing','hidden', 1, 'Check')
    make_property_setter('Item','hub_publishing_sb','hidden', 1, 'Check')
    make_property_setter('Item','more_information_section','hidden', 1, 'Check')
    make_property_setter('Item','defaults','hidden', 1, 'Check')
    make_property_setter('BOM','project','hidden', 1, 'Check')
    make_property_setter('BOM','currency_detail','hidden', 1, 'Check')
    make_property_setter('BOM','materials_section','hidden', 1, 'Check')
    make_property_setter('BOM','scrap_section','hidden', 1, 'Check')
    make_property_setter('BOM','website_section','hidden', 1, 'Check')
    make_property_setter('BOM','routing','hidden', 1, 'Check')
    make_property_setter('BOM','section_break_25','hidden', 1, 'Check')
    make_property_setter('Job Card','quality_inspection_template','hidden', 1, 'Check')
    make_property_setter('Job Card','quality_inspection','hidden', 1, 'Check')
    make_property_setter('Job Card','project','hidden', 1, 'Check')
    make_property_setter('Job Card','batch_no','hidden', 1, 'Check')
    make_property_setter('Job Card','serial_no','hidden', 1, 'Check')
    make_property_setter('Job Card','scrap_items_section','hidden', 1, 'Check')
    make_property_setter('Job Card','more_information','hidden', 1, 'Check')
    make_property_setter('Sales Order','scan_barcode','hidden', 1, 'Check')
    make_property_setter('Sales Order','terms_section_break','hidden', 1, 'Check')
    make_property_setter('Sales Order','more_info','hidden', 1, 'Check')
    make_property_setter('Sales Order','printing_details','hidden', 1, 'Check')
    make_property_setter('Sales Order','section_break_78','hidden', 1, 'Check')
    make_property_setter('Sales Order','sales_team_section_break','hidden', 1, 'Check')
    make_property_setter('Sales Order','section_break1','hidden', 1, 'Check')
    make_property_setter('Sales Order','subscription_section','hidden', 1, 'Check')
    make_property_setter('Stock Entry','inspection_required','hidden', 1, 'Check')
    make_property_setter('Stock Entry','printing_settings','hidden', 1, 'Check')
    make_property_setter('Stock Entry','more_info','hidden', 1, 'Check')
    make_property_setter('Stock Entry','scan_barcode','hidden', 1, 'Check')
    make_property_setter('Purchase Order','column_break5','hidden', 1, 'Check')
    make_property_setter('Purchase Order','subscription_section','hidden', 1, 'Check')
    make_property_setter('Purchase Order','more_info','hidden', 1, 'Check')
    make_property_setter('Purchase Order','scan_barcode','hidden', 1, 'Check')
    make_property_setter('Purchase Order','terms_section_break','hidden',1,'Check')
    make_property_setter('Purchase Receipt','more_info','hidden', 1, 'Check')
    make_property_setter('Purchase Receipt','scan_barcode','hidden', 1, 'Check')
    make_property_setter('Purchase Receipt','subscription_detail','hidden',1,'Check')
    make_property_setter('Purchase Receipt','printing_settings','hidden',1,'Check')
    make_property_setter('Purchase Receipt','terms_section_break','hidden',1,'Check')
    make_property_setter('Purchase Invoice','scan_barcode','hidden', 1, 'Check')
    make_property_setter('Purchase Invoice','terms_section_break','hidden',1,'Check')
    make_property_setter('Purchase Invoice','printing_settings','hidden',1,'Check')
    make_property_setter('Purchase Invoice','more_info','hidden',1,'Check')
    make_property_setter('Sales Invoice','terms_section_break','hidden',1,'Check')
    make_property_setter('Sales Invoice','edit_printing_settings','hidden',1,'Check')
    make_property_setter('Sales Invoice','more_information','hidden',1,'Check')
    make_property_setter('Sales Invoice','sales_team_section_break','hidden',1,'Check')
    make_property_setter('Sales Invoice','subscription_section','hidden',1,'Check')
    
    

def execute():
    create_property_setter()